name: Lock Branch
run-name: Lock Branch ${{ inputs.BRANCH }}

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: "Branch"
        type: string
        required: false

jobs:

  check-branch:
    name: Check Branch
    runs-on: [ ubuntu-latest ]
    outputs:
      isBranchCorrect: ${{steps.asdasd.outputs.isBranchCorrect}}
    steps:
      - name: "Check if branch is master or release"
        id: asdasd
        run: |
          [[ "${{inputs.BRANCH}}" == master ]] || [[ "${{inputs.BRANCH}}" == release* ]]
          isBranchCorrect=$?
          echo "isBranchCorrect=$isBranchCorrect" >> $GITHUB_OUTPUT

  lock-branch:
    name: Lock ${{inputs.BRANCH}} branch
    runs-on: [ ubuntu-latest ]
    needs: check-branch
    steps:
      - name: "Was it okay"
        run: |
          echo ${{needs.check-branch.outputs.isBranchCorrect}}
